### ISSUE TITLE
Plugin not installed

### ISSUE THREAD

**Issue by rithvikvibhu** [x211321/RGB-Config-Acer-gkbbl-0-Plasma-Widget#1]
Hey, love the plugin, I've been using it for a long time!

I'm setting up a new system and tried installing it again like last time, but it doesn't seem to work:

```
$ plasmapkg2 -u RGB-Config-Acer_0.1.4.plasmoid

Error: Plugin com.github.x211321.rgb-config-acer-gkbbl-0-plasma-widget is not installed.
```

Any idea how to install it? It's a clean os install so could be missing some dependencies, idk.

**Comment by x211321** [comment]
Hi, thanks for your feedback. 

Seems like I made a mistake in the documentation. 

The **-i** switch must be used for first install 
`plasmapkg2 -i RGB-Config-Acer_0.1.4.plasmoid`

The **-u** switch is for updating an already installed plasmoid
I probably copy-pasted the command line from the update section to the install section without catching the difference. 

Please give that a try and let me now if it works. 

Thanks.

**Comment by rithvikvibhu** [comment]
D'oh I should've read the man page for plasmapkg first. `-i` worked. 

Thanks again for the plugin!

**Comment by x211321** [comment]
Glad I could help.

Thanks for using the plugin, let me know if you ever encounter any issues.
